---
- name: install swarm
  hosts: localhost
  tasks:
  - name: copy man file
    tags: man
    copy:
      src: "{{ item }}"
      dest: /usr/local/share/man/man1/
      owner: root
      group: root
      mode: 0644
    with_fileglob:
      - /data/hooverdm/GitHub/swarm/swarm.1
  - name: copy html file
    tags: html
    copy:
      src: "{{ item }}"
      dest: /usr/local/www/hpcweb/htdocs/apps/
      owner: hooverdm
      group: webcpu
      mode: 0644
    with_fileglob:
      - /data/hooverdm/GitHub/swarm/swarm.html
  - name: copy swarm_manager script
    tags: swarm_manager
    copy:
      src: "{{ item }}"
      dest: /usr/local/sbin/
      owner: hooverdm
      group: staff
      mode: 0740
    with_fileglob:
      - /data/hooverdm/GitHub/swarm/swarm_manager
  - name: copy swarm script
    tags: swarm
    copy:
      src: "{{ item }}"
      dest: /usr/local/bin/
      owner: root
      group: root
      mode: 0755
    with_fileglob:
      - /data/hooverdm/GitHub/swarm/swarm
...

